FROM golang:1.24.2

WORKDIR /app

COPY . /app

RUN go mod download

WORKDIR /app/gobierno

# Add environment variables with default values that can be overridden
ENV RABBITMQ_HOST=rabbitmq
ENV RABBITMQ_PORT=5672

EXPOSE 50052

# Modify the command to use environment variables
CMD ["sh", "-c", "go run gobierno.go -rabbitmq_host=$RABBITMQ_HOST -rabbitmq_port=$RABBITMQ_PORT"]