FROM golang:1.24.2

WORKDIR /app

COPY . /app

RUN go mod download

WORKDIR /app/caza

ENV RABBITMQ_HOST=rabbitmq
ENV RABBITMQ_PORT=5672

EXPOSE 50052

CMD ["sh", "-c", "go run caza.go -rabbitmq_host=$RABBITMQ_HOST -rabbitmq_port=$RABBITMQ_PORT"]